baseURL = "https://ghsable.github.io/sunalog" #baseURL = "https://sunalog.tk/"
copyright = "© 2021-2022 <a href=\"https://github.com/ghsable/sunalog\">GitHub</a>, Inc."
googleAnalytics = "UA-157767797-1"
languageCode = "en-us"
theme = "github-style"
title = "sunalog"
publishDir = "docs"
pygmentsCodeFences = true
pygmentsUseClasses = true

[frontmatter]
 lastmod = ["lastmod", ":fileModTime", ":default"]

[Params]
 author = "sunalog"
 avatar = "/sunalog/images/uploads/shima.png"
 description = "Use software leverage to your advantage."
 #email = ""
 enableGitalk = false
 favicon = "/sunalog/images/github-mark.png"
 github = "ghsable"
 headerIcon = "/sunalog/images/github-mark-white.png"
 lastmod = true
 location = "Japan￤NixOS"
 rss = true
 #twitter = ""
 url = "https://ghsable.github.io"
