baseURL = "https://ghsable.github.io/sunalog/"
#baseURL = "https://sunalog.tk/"
languageCode = "en-us"
title = "sunalog"
publishDir = "docs"
googleAnalytics = "UA-157767797-1"
theme = "github-style"
copyright = "Â© 2021 <a href=\"https://github.com/ghsable/sunalog\">GitHub</a>, Inc."
pygmentsCodeFences = true
pygmentsUseClasses = true

[Params]
 author = "suna"
 description = "Use software leverage to your advantage."
 rss = true
 github = "ghsable"
 twitter = "tnsable"
 email = "suna@xmpp.is"
 url = "https://ghsable.github.io"
 avatar = 'https://ghsable.github.io/sunalog/images/uploads/shima.png'
 favicon = "/sunalog/images/github.png"
 location = "Japan"
 lastmod = true

[frontmatter]
 lastmod = ["lastmod", ":fileModTime", ":default"]

